server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: Shiv#12345
    url: jdbc:postgresql://flask-app-databasebackend.cgmlyvc8kk7s.eu-central-1.rds.amazonaws.com:5432/kol_db_aks
    username: postgres
    host_name: flask-app-databasebackend.cgmlyvc8kk7s.eu-central-1.rds.amazonaws.com
    database_name: kol_db_aks
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
constants:
  url:
    "http://localhost:8080"
  react_app:
    "http://localhost:3000"